name: cs442_mp1
description: CS 442 MP1 - Profile information page
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/1.jpeg
    - assets/images/2.jpeg
    - assets/images/3.jpeg
    - assets/images/swathi2.png
    - assets/images/network.png
    - assets/images/fullstack.png
    - assets/images/sde.png
    - assets/images/testing.png
    - assets/images/iit.png
    - assets/images/iit2.png
    - assets/images/griet.png
    - assets/images/phone.png
    - assets/images/emailicon.png
    - assets/images/home.png
    
    



  fonts:
    - family: Handlee
      fonts:
        - asset: assets/fonts/Handlee-Regular.ttf
    - family: Shantel
      fonts:
        - asset: assets/fonts/ShantellSans-VariableFont_BNCE,INFM,SPAC,wght.ttf
